---
version: 2
jobs:
  docker-lint:
    docker:
      - image: vpgrp/linter:docker-lint
    steps:
      - checkout
      - run:
          name: docker linting
          command: /usr/bin/docker-lint Dockerfile
  markdown-lint:
    docker:
      - image: markdownlint/markdownlint
    steps:
      - checkout
      - run:
          name: markdown linting
          command: mdl .
workflows:
  version: 2
  lint:
    jobs:
      - docker-lint
      - markdown-lint
