---
version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  markdown: hux/markdown@0.0.23
workflows:
  version: 2
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
      - markdown/lint
